# Generated by Django 4.2.3 on 2024-08-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('student_class', models.CharField(choices=[('1', 'Pre-Nursery'), ('2', 'Nursery'), ('3', 'LKG'), ('4', 'UKG'), ('5', 'I'), ('6', 'II'), ('7', 'III'), ('8', 'IV'), ('9', 'V'), ('10', 'VI'), ('11', 'VII'), ('12', 'VIII')], max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
